#!/usr/bin/env bash
# =============================================================================
#  Install the account API: public registration/login for example.invalid
# =============================================================================
#  Installs (as root):
#    * account-api.mjs + its node_modules, under /opt/dolphinclient/account-api
#    * dolphinclient-account-api.service (127.0.0.1:8789)
#    * the nginx snippet that proxies /account-api/ to it (no Access gate —
#      this one is public, see deploy/nginx/dolphinclient-account.conf)
#
#  A stable ACCOUNT_SECRET (the HMAC key for session tokens) is generated once
#  into /etc/dolphinclient/account.env and left alone on later runs — losing
#  it would silently invalidate every signed-in session.
#
#  SMTP for password-reset mail is optional; set it by editing
#  /etc/dolphinclient/account.env and restarting the service. Unset, /auth/forgot
#  just says so instead of failing.
#
#  Usage: sudo deploy/setup-account-api.sh
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE=/etc/dolphinclient/account.env
OPT=/opt/dolphinclient/account-api

[[ $EUID -eq 0 ]] || { echo "Please run as root (sudo)." >&2; exit 1; }
command -v node >/dev/null || { echo "node is missing." >&2; exit 1; }
command -v npm >/dev/null || { echo "npm is missing." >&2; exit 1; }

say() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }
ok()  { printf '  \033[32m✓\033[0m %s\n' "$*"; }

# ---------------------------------------------------------------------------
say "Installing account-api and its dependencies"
install -d -m 0755 "$OPT"
install -m 0644 "$ROOT/deploy/account-api.mjs" "$OPT/account-api.mjs"
install -m 0644 "$ROOT/deploy/package.json" "$OPT/package.json"
[[ -f "$ROOT/deploy/package-lock.json" ]] && install -m 0644 "$ROOT/deploy/package-lock.json" "$OPT/package-lock.json"
# better-sqlite3 is a native module — install it here, on this machine, not
# copied in from wherever the repo was checked out.
(cd "$OPT" && npm install --omit=dev --no-audit --no-fund >/dev/null)
ok "$OPT (with node_modules)"

install -d -m 0750 /etc/dolphinclient
if [[ ! -f "$ENV_FILE" ]]; then
  SECRET="$(node -e 'process.stdout.write(require("node:crypto").randomBytes(32).toString("hex"))')"
  cat > "$ENV_FILE" <<EOF
# Account API — generated by deploy/setup-account-api.sh. ACCOUNT_SECRET signs
# session tokens; changing it signs everyone out. SMTP is optional — leave the
# host empty to keep password-reset mail off.
ACCOUNT_SECRET=$SECRET
ACCOUNT_API_LISTEN=127.0.0.1:8789
ACCOUNT_SMTP_HOST=
ACCOUNT_SMTP_PORT=587
ACCOUNT_SMTP_USER=
ACCOUNT_SMTP_PASS=
ACCOUNT_SMTP_FROM=DolphinClient <user@example.invalid>
EOF
  chmod 0640 "$ENV_FILE"
  ok "$ENV_FILE created (fresh ACCOUNT_SECRET, mail off)"
else
  ok "$ENV_FILE left unchanged"
fi

cat > /etc/systemd/system/dolphinclient-account-api.service <<EOF
[Unit]
Description=DolphinClient — account API (registration, login, dashboard)
Documentation=file://$ROOT/deploy/README.md
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=$ENV_FILE
Environment=ACCOUNT_DB=/var/lib/dolphinclient/account-api/account.db
ExecStart=/usr/bin/node $OPT/account-api.mjs
Restart=always
RestartSec=2
DynamicUser=yes
StateDirectory=dolphinclient/account-api
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ProtectHome=yes
RestrictAddressFamilies=AF_INET AF_INET6
MemoryMax=192M

[Install]
WantedBy=multi-user.target
EOF
ok "dolphinclient-account-api.service"

# ---------------------------------------------------------------------------
say "Installing the nginx configuration"
backup() { [[ -f "$1" ]] && cp -a "$1" "$1.bak-$(date +%Y%m%d%H%M%S)"; :; }
backup /etc/nginx/snippets/dolphinclient-locations.conf
install -m 0644 "$ROOT/deploy/nginx/dolphinclient-locations.conf" /etc/nginx/snippets/
install -m 0644 "$ROOT/deploy/nginx/dolphinclient-account.conf" /etc/nginx/snippets/
ok "snippets/{dolphinclient-locations,dolphinclient-account}.conf"

# ---------------------------------------------------------------------------
say "Starting and checking"
systemctl daemon-reload
systemctl enable dolphinclient-account-api.service >/dev/null
systemctl restart dolphinclient-account-api.service
ok "Service running"

nginx -t
systemctl reload nginx
ok "nginx reloaded"

sleep 1
echo "  API: $(curl -fsS --max-time 5 http://127.0.0.1:8789/health || echo 'not answering')"
printf '\n\033[32mDone.\033[0m Registration and sign-in are live at https://example.invalid/register\n'
printf 'and https://example.invalid/login. Password-reset mail is off until SMTP\n'
printf 'is set in %s and the service is restarted.\n' "$ENV_FILE"
